drop extension if exists "pg_net";


  create table "public"."chauffør Afregning" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."chauffør Afregning" enable row level security;


  create table "public"."config" (
    "n" text not null,
    "v" text
      );


alter table "public"."config" enable row level security;


  create table "public"."fejlede_uploads" (
    "id" uuid not null default gen_random_uuid(),
    "chauffor" text,
    "driver_id" text,
    "filename" text,
    "fejl_besked" text,
    "billede_url" text,
    "modtaget" timestamp with time zone default now(),
    "status" text default 'ny'::text
      );


alter table "public"."fejlede_uploads" enable row level security;


  create table "public"."satser" (
    "chauffor" text not null,
    "sats1" numeric,
    "graense" numeric,
    "sats2" numeric,
    "del_med_kone" boolean default false,
    "token" text
      );



  create table "public"."slutrapporter" (
    "id" uuid not null default gen_random_uuid(),
    "dato" date,
    "slutrapport_nr" text,
    "chauffor" text,
    "indkort" numeric default 0,
    "overfort" numeric default 0,
    "kontant" numeric default 0,
    "bro_faerge" numeric default 0,
    "vagt_start" text,
    "vagt_slut" text,
    "oprettet" timestamp with time zone default now()
      );


CREATE UNIQUE INDEX "chauffør Afregning_pkey" ON public."chauffør Afregning" USING btree (id);

CREATE UNIQUE INDEX config_pkey ON public.config USING btree (n);

CREATE UNIQUE INDEX fejlede_uploads_pkey ON public.fejlede_uploads USING btree (id);

CREATE UNIQUE INDEX satser_pkey ON public.satser USING btree (chauffor);

CREATE UNIQUE INDEX slutrapporter_pkey ON public.slutrapporter USING btree (id);

CREATE UNIQUE INDEX ux_slutrapport ON public.slutrapporter USING btree (chauffor, slutrapport_nr);

alter table "public"."chauffør Afregning" add constraint "chauffør Afregning_pkey" PRIMARY KEY using index "chauffør Afregning_pkey";

alter table "public"."config" add constraint "config_pkey" PRIMARY KEY using index "config_pkey";

alter table "public"."fejlede_uploads" add constraint "fejlede_uploads_pkey" PRIMARY KEY using index "fejlede_uploads_pkey";

alter table "public"."satser" add constraint "satser_pkey" PRIMARY KEY using index "satser_pkey";

alter table "public"."slutrapporter" add constraint "slutrapporter_pkey" PRIMARY KEY using index "slutrapporter_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.fix_nattevagt_dato()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  if new.vagt_slut is not null and new.vagt_start is not null
     and new.vagt_slut < new.vagt_start then
    new.dato := new.dato - interval '1 day';
  end if;
  return new;
end $function$
;

CREATE OR REPLACE FUNCTION public.hent_alle(p_token text, p_maaned text DEFAULT NULL::text)
 RETURNS SETOF public.v_lonseddel
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select L.* from v_lonseddel L
  where exists (select 1 from config where n='owner_token' and v=p_token)
    and (p_maaned is null or L.regnskabsmaaned = p_maaned);
$function$
;

CREATE OR REPLACE FUNCTION public.hent_fejlede(p_token text)
 RETURNS SETOF public.fejlede_uploads
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select f.* from fejlede_uploads f
  where exists (select 1 from config where n='owner_token' and v = p_token)
  order by f.modtaget desc;
$function$
;

CREATE OR REPLACE FUNCTION public.hent_kvittering(p_token text, p_maaned text DEFAULT NULL::text)
 RETURNS SETOF public.v_lonseddel
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select L.* from v_lonseddel L
  where L.chauffor = (select chauffor from satser where trim(token) = trim(p_token))
    and (p_maaned is null or L.regnskabsmaaned = p_maaned);
$function$
;

CREATE OR REPLACE FUNCTION public.hent_ture(p_token text, p_maaned text)
 RETURNS TABLE(dato date, slutrapport_nr text, indkort numeric, overfort numeric, kontant numeric, vagt_start text, vagt_slut text, chauffor text)
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select d.dato,d.slutrapport_nr,d.indkort,d.overfort,d.kontant,d.vagt_start,d.vagt_slut,d.chauffor
  from v_data d
  where d.regnskabsmaaned = p_maaned
    and ( d.chauffor = (select chauffor from satser where token = p_token)
          or exists(select 1 from config where n='owner_token' and v=p_token) )
  order by d.dato;
$function$
;

CREATE OR REPLACE FUNCTION public.lonseddel(p_chauffor text, p_maaned text)
 RETURNS TABLE(chauffor text, regnskabsmaaned text, antal_ture bigint, indkort_i_alt numeric, kontant_i_alt numeric, bro_faerge_i_alt numeric, model text, andel_brutto numeric, andel_op_til_graensen numeric, andel_over_graensen numeric, heraf_chauffor_halvdel numeric, heraf_kone_halvdel numeric, kontant_pr_person numeric, til_udbetaling numeric)
 LANGUAGE sql
AS $function$
  with pr as (
    select
      d.chauffor,
      d.regnskabsmaaned,
      count(*)            as ture,
      sum(d.indkort)      as indkort,
      sum(d.kontant)      as kontant,
      sum(d.bro_faerge)   as bro_faerge
    from v_data d
    where d.chauffor = p_chauffor and d.regnskabsmaaned = p_maaned
    group by d.chauffor, d.regnskabsmaaned
  )
  select
    pr.chauffor,
    pr.regnskabsmaaned,
    pr.ture,
    round(pr.indkort,2),
    round(pr.kontant,2),
    round(pr.bro_faerge,2),
    case when sat.graense >= 10000000
         then to_char(sat.sats1*100,'FM990')||'%'
         else to_char(sat.sats1*100,'FM990')||'% op til '||to_char(sat.graense,'FM999G999')||', '||to_char(sat.sats2*100,'FM990')||'% derover'
    end as model,
    round(least(pr.indkort,sat.graense)*sat.sats1 + greatest(pr.indkort-sat.graense,0)*sat.sats2, 2) as andel_brutto,
    case when sat.graense < 10000000 and pr.indkort > sat.graense
         then round(least(pr.indkort,sat.graense)*sat.sats1,2) end,
    case when pr.indkort > sat.graense
         then round(greatest(pr.indkort-sat.graense,0)*sat.sats2,2) end,
    case when sat.del_med_kone
         then round((least(pr.indkort,sat.graense)*sat.sats1 + greatest(pr.indkort-sat.graense,0)*sat.sats2)/2,2) end,
    case when sat.del_med_kone
         then round((least(pr.indkort,sat.graense)*sat.sats1 + greatest(pr.indkort-sat.graense,0)*sat.sats2)/2,2) end,
    case when sat.del_med_kone then round(pr.kontant/2,2) end,
    round(least(pr.indkort,sat.graense)*sat.sats1 + greatest(pr.indkort-sat.graense,0)*sat.sats2 - pr.kontant - pr.bro_faerge, 2) as til_udbetaling
  from pr
  join satser sat on sat.chauffor = pr.chauffor;
$function$
;

CREATE OR REPLACE FUNCTION public.marker_fejl(p_token text, p_id uuid, p_status text)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  update fejlede_uploads
  set status = p_status
  where id = p_id
    and exists (select 1 from config where n='owner_token' and v = p_token);
$function$
;

create or replace view "public"."v_advarsler" as  SELECT id,
    dato,
    slutrapport_nr,
    chauffor,
    indkort,
    overfort,
    kontant,
    bro_faerge,
    vagt_start,
    vagt_slut,
    oprettet
   FROM public.slutrapporter
  WHERE (dato IS NULL);


create or replace view "public"."v_data" as  SELECT id,
    dato,
    slutrapport_nr,
    chauffor,
    indkort,
    overfort,
    kontant,
    bro_faerge,
    vagt_start,
    vagt_slut,
    oprettet,
    to_char((
        CASE
            WHEN (EXTRACT(day FROM dato) >= (28)::numeric) THEN ((date_trunc('month'::text, (dato)::timestamp with time zone) + '1 mon'::interval))::date
            ELSE dato
        END)::timestamp with time zone, 'YYYY-MM'::text) AS regnskabsmaaned
   FROM public.slutrapporter s;


create or replace view "public"."v_dato_tjek" as  SELECT id,
    chauffor,
    slutrapport_nr,
    dato,
    indkort
   FROM public.slutrapporter
  WHERE ((dato < (CURRENT_DATE - '90 days'::interval)) OR (dato > (CURRENT_DATE + '7 days'::interval)))
  ORDER BY dato;


create or replace view "public"."v_dubletter" as  SELECT chauffor,
    dato,
    indkort,
    count(*) AS antal
   FROM public.slutrapporter
  GROUP BY chauffor, dato, indkort
 HAVING (count(*) > 1);


create or replace view "public"."v_lonseddel" as  WITH pr AS (
         SELECT d.chauffor,
            d.regnskabsmaaned,
            count(*) AS antal_ture,
            sum(d.indkort) AS indkort,
            sum(d.overfort) AS overfort,
            sum(d.kontant) AS kontant,
            sum(d.bro_faerge) AS bro_faerge
           FROM public.v_data d
          GROUP BY d.chauffor, d.regnskabsmaaned
        )
 SELECT pr.chauffor,
    pr.regnskabsmaaned,
    pr.antal_ture,
    round(pr.indkort, 2) AS indkort_i_alt,
    round(pr.overfort, 2) AS overfort_i_alt,
    round((pr.indkort - pr.overfort), 2) AS afregn_difference,
    round(pr.kontant, 2) AS kontant_i_alt,
    round(pr.bro_faerge, 2) AS bro_faerge_i_alt,
        CASE
            WHEN (sat.graense >= (10000000)::numeric) THEN ((((sat.sats1 * (100)::numeric))::integer)::text || '%'::text)
            ELSE ((((((((sat.sats1 * (100)::numeric))::integer)::text || '% op til '::text) || ((sat.graense)::bigint)::text) || ', '::text) || (((sat.sats2 * (100)::numeric))::integer)::text) || '% derover'::text)
        END AS model,
    round(((LEAST(pr.indkort, sat.graense) * sat.sats1) + (GREATEST((pr.indkort - sat.graense), (0)::numeric) * sat.sats2)), 2) AS andel_brutto,
    round(
        CASE
            WHEN ((sat.graense < (10000000)::numeric) AND (pr.indkort > sat.graense)) THEN (LEAST(pr.indkort, sat.graense) * sat.sats1)
            ELSE NULL::numeric
        END, 2) AS andel_op_til_graensen,
    round(
        CASE
            WHEN (pr.indkort > sat.graense) THEN (GREATEST((pr.indkort - sat.graense), (0)::numeric) * sat.sats2)
            ELSE NULL::numeric
        END, 2) AS andel_over_graensen,
    round(
        CASE
            WHEN sat.del_med_kone THEN (((LEAST(pr.indkort, sat.graense) * sat.sats1) + (GREATEST((pr.indkort - sat.graense), (0)::numeric) * sat.sats2)) / (2)::numeric)
            ELSE NULL::numeric
        END, 2) AS heraf_chauffor_halvdel,
    round(
        CASE
            WHEN sat.del_med_kone THEN (((LEAST(pr.indkort, sat.graense) * sat.sats1) + (GREATEST((pr.indkort - sat.graense), (0)::numeric) * sat.sats2)) / (2)::numeric)
            ELSE NULL::numeric
        END, 2) AS heraf_kone_halvdel,
    round(
        CASE
            WHEN sat.del_med_kone THEN (pr.kontant / (2)::numeric)
            ELSE NULL::numeric
        END, 2) AS kontant_pr_person,
    round(((((LEAST(pr.indkort, sat.graense) * sat.sats1) + (GREATEST((pr.indkort - sat.graense), (0)::numeric) * sat.sats2)) - pr.kontant) - pr.bro_faerge), 2) AS til_udbetaling
   FROM (pr
     JOIN public.satser sat ON ((sat.chauffor = pr.chauffor)))
  ORDER BY pr.regnskabsmaaned, pr.chauffor;


create or replace view "public"."v_lonseddel_pen" as  SELECT l.chauffor,
    l.regnskabsmaaned,
    x.nr,
    x.linje,
    x.vaerdi
   FROM (public.v_lonseddel l
     CROSS JOIN LATERAL ( VALUES (1,'Antal ture'::text,(l.antal_ture)::text), (2,'Indkørt i alt'::text,to_char(l.indkort_i_alt, 'FM999990.00'::text)), (3,'Overført i alt'::text,to_char(l.overfort_i_alt, 'FM999990.00'::text)), (4,'Afregn (difference)'::text,to_char(l.afregn_difference, 'FM999990.00'::text)), (5,'Kontant i alt'::text,to_char(l.kontant_i_alt, 'FM999990.00'::text)), (6,'Bro/Færge i alt'::text,to_char(l.bro_faerge_i_alt, 'FM999990.00'::text)), (7,'Model (sats)'::text,l.model), (8,'Andel i alt (brutto)'::text,to_char(l.andel_brutto, 'FM999990.00'::text)), (9,'   . Andel op til grænsen'::text,COALESCE(to_char(l.andel_op_til_graensen, 'FM999990.00'::text), '-'::text)), (10,'   . Andel over grænsen'::text,COALESCE(to_char(l.andel_over_graensen, 'FM999990.00'::text), '-'::text)), (11,'   . Heraf chauffør (halvdel)'::text,COALESCE(to_char(l.heraf_chauffor_halvdel, 'FM999990.00'::text), '-'::text)), (12,'   . Heraf kone (halvdel)'::text,COALESCE(to_char(l.heraf_kone_halvdel, 'FM999990.00'::text), '-'::text)), (13,'   . Kontant pr. person (halvdel)'::text,COALESCE(to_char(l.kontant_pr_person, 'FM999990.00'::text), '-'::text)), (14,'TIL UDBETALING'::text,to_char(l.til_udbetaling, 'FM999990.00'::text))) x(nr, linje, vaerdi));


create or replace view "public"."v_afregning" as  WITH pr AS (
         SELECT d.regnskabsmaaned,
            d.chauffor,
            count(*) AS ture,
            sum(d.indkort) AS indkort,
            sum(d.kontant) AS kontant,
            sum(d.bro_faerge) AS bro_faerge
           FROM public.v_data d
          GROUP BY d.regnskabsmaaned, d.chauffor
        )
 SELECT pr.regnskabsmaaned,
    pr.chauffor,
    pr.ture,
    round(pr.indkort, 2) AS indkort,
    round(pr.kontant, 2) AS kontant,
    round(pr.bro_faerge, 2) AS bro_faerge,
    round(((LEAST(pr.indkort, sat.graense) * sat.sats1) + (GREATEST((pr.indkort - sat.graense), (0)::numeric) * sat.sats2)), 2) AS andel,
    round(((((LEAST(pr.indkort, sat.graense) * sat.sats1) + (GREATEST((pr.indkort - sat.graense), (0)::numeric) * sat.sats2)) - pr.kontant) - pr.bro_faerge), 2) AS til_udbetaling
   FROM (pr
     JOIN public.satser sat ON ((sat.chauffor = pr.chauffor)))
  ORDER BY pr.regnskabsmaaned, pr.chauffor;


grant delete on table "public"."chauffør Afregning" to "anon";

grant insert on table "public"."chauffør Afregning" to "anon";

grant references on table "public"."chauffør Afregning" to "anon";

grant select on table "public"."chauffør Afregning" to "anon";

grant trigger on table "public"."chauffør Afregning" to "anon";

grant truncate on table "public"."chauffør Afregning" to "anon";

grant update on table "public"."chauffør Afregning" to "anon";

grant delete on table "public"."chauffør Afregning" to "authenticated";

grant insert on table "public"."chauffør Afregning" to "authenticated";

grant references on table "public"."chauffør Afregning" to "authenticated";

grant select on table "public"."chauffør Afregning" to "authenticated";

grant trigger on table "public"."chauffør Afregning" to "authenticated";

grant truncate on table "public"."chauffør Afregning" to "authenticated";

grant update on table "public"."chauffør Afregning" to "authenticated";

grant delete on table "public"."chauffør Afregning" to "service_role";

grant insert on table "public"."chauffør Afregning" to "service_role";

grant references on table "public"."chauffør Afregning" to "service_role";

grant select on table "public"."chauffør Afregning" to "service_role";

grant trigger on table "public"."chauffør Afregning" to "service_role";

grant truncate on table "public"."chauffør Afregning" to "service_role";

grant update on table "public"."chauffør Afregning" to "service_role";

grant delete on table "public"."config" to "anon";

grant insert on table "public"."config" to "anon";

grant references on table "public"."config" to "anon";

grant trigger on table "public"."config" to "anon";

grant truncate on table "public"."config" to "anon";

grant update on table "public"."config" to "anon";

grant delete on table "public"."config" to "authenticated";

grant insert on table "public"."config" to "authenticated";

grant references on table "public"."config" to "authenticated";

grant select on table "public"."config" to "authenticated";

grant trigger on table "public"."config" to "authenticated";

grant truncate on table "public"."config" to "authenticated";

grant update on table "public"."config" to "authenticated";

grant delete on table "public"."config" to "service_role";

grant insert on table "public"."config" to "service_role";

grant references on table "public"."config" to "service_role";

grant select on table "public"."config" to "service_role";

grant trigger on table "public"."config" to "service_role";

grant truncate on table "public"."config" to "service_role";

grant update on table "public"."config" to "service_role";

grant delete on table "public"."fejlede_uploads" to "anon";

grant insert on table "public"."fejlede_uploads" to "anon";

grant references on table "public"."fejlede_uploads" to "anon";

grant trigger on table "public"."fejlede_uploads" to "anon";

grant truncate on table "public"."fejlede_uploads" to "anon";

grant update on table "public"."fejlede_uploads" to "anon";

grant delete on table "public"."fejlede_uploads" to "authenticated";

grant insert on table "public"."fejlede_uploads" to "authenticated";

grant references on table "public"."fejlede_uploads" to "authenticated";

grant select on table "public"."fejlede_uploads" to "authenticated";

grant trigger on table "public"."fejlede_uploads" to "authenticated";

grant truncate on table "public"."fejlede_uploads" to "authenticated";

grant update on table "public"."fejlede_uploads" to "authenticated";

grant delete on table "public"."fejlede_uploads" to "service_role";

grant insert on table "public"."fejlede_uploads" to "service_role";

grant references on table "public"."fejlede_uploads" to "service_role";

grant select on table "public"."fejlede_uploads" to "service_role";

grant trigger on table "public"."fejlede_uploads" to "service_role";

grant truncate on table "public"."fejlede_uploads" to "service_role";

grant update on table "public"."fejlede_uploads" to "service_role";

grant delete on table "public"."satser" to "anon";

grant insert on table "public"."satser" to "anon";

grant references on table "public"."satser" to "anon";

grant select on table "public"."satser" to "anon";

grant trigger on table "public"."satser" to "anon";

grant truncate on table "public"."satser" to "anon";

grant update on table "public"."satser" to "anon";

grant delete on table "public"."satser" to "authenticated";

grant insert on table "public"."satser" to "authenticated";

grant references on table "public"."satser" to "authenticated";

grant select on table "public"."satser" to "authenticated";

grant trigger on table "public"."satser" to "authenticated";

grant truncate on table "public"."satser" to "authenticated";

grant update on table "public"."satser" to "authenticated";

grant delete on table "public"."satser" to "service_role";

grant insert on table "public"."satser" to "service_role";

grant references on table "public"."satser" to "service_role";

grant select on table "public"."satser" to "service_role";

grant trigger on table "public"."satser" to "service_role";

grant truncate on table "public"."satser" to "service_role";

grant update on table "public"."satser" to "service_role";

grant delete on table "public"."slutrapporter" to "anon";

grant insert on table "public"."slutrapporter" to "anon";

grant references on table "public"."slutrapporter" to "anon";

grant trigger on table "public"."slutrapporter" to "anon";

grant truncate on table "public"."slutrapporter" to "anon";

grant update on table "public"."slutrapporter" to "anon";

grant delete on table "public"."slutrapporter" to "authenticated";

grant insert on table "public"."slutrapporter" to "authenticated";

grant references on table "public"."slutrapporter" to "authenticated";

grant select on table "public"."slutrapporter" to "authenticated";

grant trigger on table "public"."slutrapporter" to "authenticated";

grant truncate on table "public"."slutrapporter" to "authenticated";

grant update on table "public"."slutrapporter" to "authenticated";

grant delete on table "public"."slutrapporter" to "service_role";

grant insert on table "public"."slutrapporter" to "service_role";

grant references on table "public"."slutrapporter" to "service_role";

grant select on table "public"."slutrapporter" to "service_role";

grant trigger on table "public"."slutrapporter" to "service_role";

grant truncate on table "public"."slutrapporter" to "service_role";

grant update on table "public"."slutrapporter" to "service_role";

CREATE TRIGGER trg_nattevagt BEFORE INSERT ON public.slutrapporter FOR EACH ROW EXECUTE FUNCTION public.fix_nattevagt_dato();


